name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: berto-dev
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          base: activity, repositories
          base_indepth: yes
          config_display: columns
          config_octicon: yes
          config_padding: 0, 10 + 15%
          config_timezone: Europe/Rome
          plugin_activity: yes
          plugin_activity_days: 25
          plugin_activity_filter: all
          plugin_activity_limit: 3
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_habits: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          plugin_traffic: yes
